# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: arkhn.fhir.fr.cohort360
canonical: http://fhir.arkhn.com/cohort360
version: 0.1.1
name: Cohort360ImplementationGuide
title: Cohort360 Implementation Guide
status: draft
publisher:
  name: Arkhn
  url: http://arkhn.com
contact:
  - name: Nicolas Riss
    telecom:
      - system: email
        value: nicolas@arkhn.com
description: The cohort 360 implementation guide developed and maintained by Arkhn to indicate how to use specific profiles for cohort360 implementation
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Artifacts Summary: artifacts.html
  Downloads: downloads.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
    "Arkhn website ": new-tab http://arkhn.com/
groups:
  UsedResources:
    name: Used Resources
    description: Resources used by cohort360
    resources:
      - StructureDefinition/cohort-condition
      - StructureDefinition/cohort-document
      - StructureDefinition/cohort-encounter
      - StructureDefinition/cohort-organization
      - StructureDefinition/cohort-patient
      - StructureDefinition/cohort-practitioner
      - StructureDefinition/cohort-procedure
      - StructureDefinition/cohort-ghm
      - StructureDefinition/cohort-body-height
      - StructureDefinition/cohort-body-weight
      - StructureDefinition/cohort-lab-observation
  CreatedResources:
    name: Created Resources
    description: Resources created by cohort360
    resources:
      - StructureDefinition/cohort-group
      - StructureDefinition/practitioner-consent
      - StructureDefinition/refused-research-consent
